#############################################################################
# Makefile for building: rotation_combinations_tested_in_ngl
# Generated by qmake (3.0) (Qt 5.6.1)
# Project:  rotation_combinations_tested_in_ngl.pro
# Template: app
# Command: /home/yannis/Qt/5.6/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile rotation_combinations_tested_in_ngl.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DNGL_DEBUG -DLINUX -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -msse -msse2 -msse3 -march=native -march=native -g -std=gnu++0x -Wall -W -Wno-unused-parameter -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/home/yannis/NGL/include -I/home/yannis/Qt/5.6/gcc_64/include -I/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL -I/home/yannis/Qt/5.6/gcc_64/include/QtWidgets -I/home/yannis/Qt/5.6/gcc_64/include/QtGui -I/home/yannis/Qt/5.6/gcc_64/include/QtCore -Imoc -I/home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++
QMAKE         = /home/yannis/Qt/5.6/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = rotation_combinations_tested_in_ngl1.0.0
DISTDIR = /tmp/rotation_combinations_tested_in_ngl/obj/rotation_combinations_tested_in_ngl1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/yannis/Qt/5.6/gcc_64/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -L/$(HOME)/NGL/lib -l NGL -L/home/yannis/Qt/5.6/gcc_64/lib -lQt5OpenGL -L/usr/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/main.cpp \
		src/NGLScene.cpp \
		src/OpenGLWindow.cpp moc/moc_OpenGLWindow.cpp
OBJECTS       = obj/main.o \
		obj/NGLScene.o \
		obj/OpenGLWindow.o \
		obj/moc_OpenGLWindow.o
DIST          = rotation_combinations_tested_in_ngl.pro include/NGLScene.h \
		include/OpenGLWindow.h src/main.cpp \
		src/NGLScene.cpp \
		src/OpenGLWindow.cpp
QMAKE_TARGET  = rotation_combinations_tested_in_ngl
DESTDIR       = 
TARGET        = rotation_combinations_tested_in_ngl


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rotation_combinations_tested_in_ngl.pro .qmake.cache /home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf /home/yannis/Qt/5.6/gcc_64/mkspecs/features/spec_pre.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/unix.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/linux.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/qconfig.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt_functions.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt_config.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/default_pre.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/resolve_config.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/default_post.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qml_debug.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/warn_on.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/resources.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/moc.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/uic.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/unix/thread.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/file_copies.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/exceptions.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/yacc.prf \
		/home/yannis/Qt/5.6/gcc_64/mkspecs/features/lex.prf \
		rotation_combinations_tested_in_ngl.pro \
		/home/yannis/Qt/5.6/gcc_64/lib/libQt5OpenGL.prl \
		/home/yannis/Qt/5.6/gcc_64/lib/libQt5Widgets.prl \
		/home/yannis/Qt/5.6/gcc_64/lib/libQt5Gui.prl \
		/home/yannis/Qt/5.6/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile rotation_combinations_tested_in_ngl.pro
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/spec_pre.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/unix.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/linux.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/sanitize.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/gcc-base.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/g++-base.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/common/g++-unix.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/qconfig.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_labscontrols_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_labstemplates_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt_functions.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt_config.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/default_pre.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/resolve_config.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/default_post.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qml_debug.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/warn_on.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/qt.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/resources.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/moc.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/unix/opengl.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/uic.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/unix/thread.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/file_copies.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/testcase_targets.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/exceptions.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/yacc.prf:
/home/yannis/Qt/5.6/gcc_64/mkspecs/features/lex.prf:
rotation_combinations_tested_in_ngl.pro:
/home/yannis/Qt/5.6/gcc_64/lib/libQt5OpenGL.prl:
/home/yannis/Qt/5.6/gcc_64/lib/libQt5Widgets.prl:
/home/yannis/Qt/5.6/gcc_64/lib/libQt5Gui.prl:
/home/yannis/Qt/5.6/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug -o Makefile rotation_combinations_tested_in_ngl.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/NGLScene.h include/OpenGLWindow.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/NGLScene.cpp src/OpenGLWindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc/moc_OpenGLWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_OpenGLWindow.cpp
moc/moc_OpenGLWindow.cpp: /home/yannis/Qt/5.6/gcc_64/include/QtGui/QWindow \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QObject \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobject.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qnamespace.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qglobal.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qconfig.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qfeatures.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qisenum.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlogging.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qflags.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmutex.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qnumeric.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstring.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qchar.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbytearray.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qrefcount.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qarraydata.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qiterator.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qpair.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringlist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qregexp.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmetatype.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QEvent \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QMargins \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmargins.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QRect \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qrect.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsize.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qpoint.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qsurface.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qicon.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpixmap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qcolor.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qrgb.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qrgba64.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qshareddata.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qhash.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qimage.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtransform.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qmatrix.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpolygon.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvector.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qregion.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdatastream.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qiodevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qline.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qcursor.h \
		include/OpenGLWindow.h
	/home/yannis/Qt/5.6/gcc_64/bin/moc $(DEFINES) -I/home/yannis/Qt/5.6/gcc_64/mkspecs/linux-g++ -I/tmp/rotation_combinations_tested_in_ngl -I/tmp/rotation_combinations_tested_in_ngl/include -I/home/yannis/NGL/include -I/home/yannis/Qt/5.6/gcc_64/include -I/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL -I/home/yannis/Qt/5.6/gcc_64/include/QtWidgets -I/home/yannis/Qt/5.6/gcc_64/include/QtGui -I/home/yannis/Qt/5.6/gcc_64/include/QtCore include/OpenGLWindow.h -o moc/moc_OpenGLWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/main.o: src/main.cpp include/OpenGLWindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QWindow \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QObject \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobject.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qnamespace.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qglobal.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qconfig.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qfeatures.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qisenum.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlogging.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qflags.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmutex.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qnumeric.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstring.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qchar.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbytearray.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qrefcount.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qarraydata.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qiterator.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qpair.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringlist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qregexp.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmetatype.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QEvent \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QMargins \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmargins.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QRect \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qrect.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsize.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qpoint.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qsurface.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qicon.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpixmap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qcolor.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qrgb.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qrgba64.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qshareddata.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qhash.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qimage.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtransform.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qmatrix.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpolygon.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvector.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qregion.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdatastream.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qiodevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qline.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qcursor.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QGuiApplication \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qguiapplication.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcoreapplication.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qeventloop.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qinputmethod.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlocale.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvariant.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdebug.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtextstream.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qset.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		include/NGLScene.h \
		/home/yannis/NGL/include/ngl/Camera.h \
		/home/yannis/NGL/include/ngl/Types.h \
		/home/yannis/NGL/include/ngl/glew.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL/QGLContext \
		/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL/qgl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopengl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qt_windows.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopengles2ext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtWidgets/qwidget.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpalette.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qbrush.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfont.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfontmetrics.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qkeysequence.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qevent.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qurl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qurlquery.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qfile.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qfiledevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qvector2d.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtouchdevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpaintengine.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpainter.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtextoption.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpen.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QSurfaceFormat \
		/home/yannis/NGL/include/ngl/Vec4.h \
		/home/yannis/NGL/include/ngl/Vec2.h \
		/home/yannis/NGL/include/ngl/Vec3.h \
		/home/yannis/NGL/include/ngl/Mat4.h \
		/home/yannis/NGL/include/ngl/RibExport.h \
		/home/yannis/NGL/include/ngl/Plane.h \
		/home/yannis/NGL/include/ngl/AABB.h \
		/home/yannis/NGL/include/ngl/BBox.h \
		/home/yannis/NGL/include/ngl/AbstractVAO.h \
		/home/yannis/NGL/include/ngl/Colour.h \
		/home/yannis/NGL/include/ngl/Light.h \
		/home/yannis/NGL/include/ngl/Text.h \
		/home/yannis/NGL/include/ngl/VAOFactory.h \
		/home/yannis/NGL/include/ngl/SimpleVAO.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QFont \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QTime \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdatetime.h \
		/home/yannis/NGL/include/ngl/Transformation.h \
		/home/yannis/NGL/include/ngl/NGLassert.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QOpenGLWindow \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglwindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QPaintDeviceWindow \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QPaintDevice \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QOpenGLContext \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglcontext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QScopedPointer \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QImage
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o src/main.cpp

obj/NGLScene.o: src/NGLScene.cpp /home/yannis/Qt/5.6/gcc_64/include/QtGui/QMouseEvent \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qevent.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qglobal.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qconfig.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qfeatures.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qisenum.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlogging.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qflags.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmutex.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qnumeric.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qnamespace.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobject.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstring.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qchar.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbytearray.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qrefcount.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qarraydata.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qiterator.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qpair.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringlist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qregexp.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmetatype.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qregion.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qrect.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmargins.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsize.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qpoint.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdatastream.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qiodevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qkeysequence.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvariant.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdebug.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qhash.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtextstream.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlocale.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qshareddata.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvector.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qset.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qurl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qurlquery.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qfile.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qfiledevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qvector2d.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtouchdevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QGuiApplication \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qguiapplication.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcoreapplication.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qeventloop.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qinputmethod.h \
		include/NGLScene.h \
		/home/yannis/NGL/include/ngl/Camera.h \
		/home/yannis/NGL/include/ngl/Types.h \
		/home/yannis/NGL/include/ngl/glew.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL/QGLContext \
		/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL/qgl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopengl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qt_windows.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopengles2ext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtWidgets/qwidget.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpalette.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qcolor.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qrgb.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qrgba64.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qbrush.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qmatrix.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpolygon.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qline.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtransform.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qimage.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpixmap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfont.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfontmetrics.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qcursor.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpaintengine.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpainter.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtextoption.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpen.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL/qglcolormap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtOpenGL/qtopenglglobal.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QSurfaceFormat \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/yannis/NGL/include/ngl/Vec4.h \
		/home/yannis/NGL/include/ngl/Vec2.h \
		/home/yannis/NGL/include/ngl/Vec3.h \
		/home/yannis/NGL/include/ngl/Mat4.h \
		/home/yannis/NGL/include/ngl/RibExport.h \
		/home/yannis/NGL/include/ngl/Plane.h \
		/home/yannis/NGL/include/ngl/AABB.h \
		/home/yannis/NGL/include/ngl/BBox.h \
		/home/yannis/NGL/include/ngl/AbstractVAO.h \
		/home/yannis/NGL/include/ngl/Colour.h \
		/home/yannis/NGL/include/ngl/Light.h \
		/home/yannis/NGL/include/ngl/Text.h \
		/home/yannis/NGL/include/ngl/VAOFactory.h \
		/home/yannis/NGL/include/ngl/SimpleVAO.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QFont \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QTime \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdatetime.h \
		/home/yannis/NGL/include/ngl/Transformation.h \
		/home/yannis/NGL/include/ngl/NGLassert.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QOpenGLWindow \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglwindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QPaintDeviceWindow \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpaintdevicewindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QWindow \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QObject \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QEvent \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QMargins \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QRect \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qsurface.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qicon.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QPaintDevice \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QOpenGLContext \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglcontext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QScopedPointer \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QImage \
		/home/yannis/NGL/include/ngl/Material.h \
		/home/yannis/NGL/include/ngl/NGLInit.h \
		/home/yannis/NGL/include/ngl/Singleton.h \
		/home/yannis/NGL/include/ngl/VAOPrimitives.h \
		/home/yannis/NGL/include/ngl/ShaderLib.h \
		/home/yannis/NGL/include/ngl/Shader.h \
		/home/yannis/NGL/include/ngl/ShaderProgram.h \
		/home/yannis/NGL/include/ngl/Util.h \
		/home/yannis/NGL/include/ngl/Mat3.h \
		/home/yannis/NGL/include/ngl/Quaternion.h \
		/home/yannis/NGL/include/ngl/MultiBufferVAO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/NGLScene.o src/NGLScene.cpp

obj/OpenGLWindow.o: src/OpenGLWindow.cpp include/OpenGLWindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QWindow \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindow.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QObject \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobject.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobjectdefs.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qnamespace.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qglobal.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qconfig.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qfeatures.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsystemdetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qprocessordetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtypeinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtypetraits.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qisenum.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsysinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlogging.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qflags.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbasicatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qgenericatomic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_x86.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qatomic_unix.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qglobalstatic.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmutex.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qnumeric.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qversiontagging.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstring.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qchar.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbytearray.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qrefcount.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qarraydata.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringbuilder.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qalgorithms.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qiterator.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qhashfunctions.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qpair.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qbytearraylist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringlist.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qregexp.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qstringmatcher.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcoreevent.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qscopedpointer.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmetatype.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qobject_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QEvent \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QMargins \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmargins.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QRect \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qrect.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsize.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qpoint.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qsurface.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qsurfaceformat.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindowdefs.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qicon.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpixmap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpaintdevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qcolor.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qrgb.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qrgba64.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsharedpointer.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qshareddata.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qhash.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qimage.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpixelformat.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtransform.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qmatrix.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpolygon.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvector.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qregion.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdatastream.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qiodevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qline.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpainterpath.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qcursor.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QCoreApplication \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcoreapplication.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qeventloop.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QOpenGLContext \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglcontext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/QScopedPointer \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QSurfaceFormat \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopengl.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qt_windows.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopengles2ext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglext.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglversionfunctions.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qvariant.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qmap.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qdebug.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qtextstream.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qlocale.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qset.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QOpenGLPaintDevice \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qopenglpaintdevice.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/QPainter \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpainter.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qtextoption.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qpen.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qbrush.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfontinfo.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfont.h \
		/home/yannis/Qt/5.6/gcc_64/include/QtGui/qfontmetrics.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/OpenGLWindow.o src/OpenGLWindow.cpp

obj/moc_OpenGLWindow.o: moc/moc_OpenGLWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_OpenGLWindow.o moc/moc_OpenGLWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

